### ISSUE TITLE
It should be possible to provide a list

### ISSUE THREAD

**Issue by steinbrueckri** [p1nkun1c0rns/prometheus-operator-lint-action#11]
```yaml
  with:
    path: ['./dev/monitoring/','./test/monitoring/']
    file_extension: *.yaml
    exclude: dashboard
```
